<a href="https://colab.research.google.com/github/Dheer08/Google-Colab/blob/main/Data_Preparation_Breast_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Loading Libraries
from pandas import read_csv, get_dummies, DataFrame
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [2]:
data=read_csv('/content/Breast_Cancer.csv')

In [3]:
data

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,62,Other,Married,T1,N1,IIA,Moderately differentiated,2,Regional,9,Positive,Positive,1,1,49,Alive
4020,56,White,Divorced,T2,N2,IIIA,Moderately differentiated,2,Regional,46,Positive,Positive,14,8,69,Alive
4021,68,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,22,Positive,Negative,11,3,69,Alive
4022,58,Black,Divorced,T2,N1,IIB,Moderately differentiated,2,Regional,44,Positive,Positive,11,1,72,Alive
4023,46,White,Married,T2,N1,IIB,Moderately differentiated,2,Regional,30,Positive,Positive,7,2,100,Alive

In [5]:
data.describe()

,Age,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months
count,4024.000000,4024.000000,4024.000000,4024.000000,4024.000000
mean,53.972167,30.473658,14.357107,4.158052,71.297962
std,8.963134,21.119696,8.099675,5.109331,22.921430
min,30.000000,1.000000,1.000000,1.000000,1.000000
25%,47.000000,16.000000,9.000000,1.000000,56.000000
50%,54.000000,25.000000,14.000000,2.000000,73.000000
75%,61.000000,38.000000,19.000000,5.000000,90.000000
max,69.000000,140.000000,61.000000,46.000000,107.000000

In [6]:
data.shape

(4024, 16)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   object
dtypes: int64(5), object(11)
memory usage: 503.1+ KB

In [8]:
data['Race'].unique()

array(['White', 'Black', 'Other'], dtype=object)

In [19]:
data['T Stage '].unique()

array(['T1', 'T2', 'T3', 'T4'], dtype=object)

In [18]:
for col in data.select_dtypes(include='object').columns:
    print(f"Column: {col}")
    print(data[col].unique())
    print("-" * 30)

Column: Race
['White' 'Black' 'Other']
------------------------------
Column: Marital Status
['Married' 'Divorced' 'Single ' 'Widowed' 'Separated']
------------------------------
Column: T Stage
['T1' 'T2' 'T3' 'T4']
------------------------------
Column: N Stage
['N1' 'N2' 'N3']
------------------------------
Column: 6th Stage
['IIA' 'IIIA' 'IIIC' 'IIB' 'IIIB']
------------------------------
Column: differentiate
['Poorly differentiated' 'Moderately differentiated' 'Well differentiated'
 'Undifferentiated']
------------------------------
Column: Grade
['3' '2' '1' ' anaplastic; Grade IV']
------------------------------
Column: A Stage
['Regional' 'Distant']
------------------------------
Column: Estrogen Status
['Positive' 'Negative']
------------------------------
Column: Progesterone Status
['Positive' 'Negative']
------------------------------
Column: Status
['Alive' 'Dead']
------------------------------

In [20]:
data['A Stage']=data['A Stage'].map({'Regional':0, 'Distant':1})

In [21]:
data['Estrogen Status']=data['Estrogen Status'].map({'Positive':0, 'Negative':1})

In [22]:
data['Progesterone Status']=data['Progesterone Status'].map({'Positive':0, 'Negative':1})

In [23]:
data['Status']=data['Status'].map({'Alive':0, 'Dead':1})

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   int64
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   int64
 11  Progesterone Status     4024 non-null   int64
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   int64
dtypes: int64(9), object(7)
memory usage: 503.1+ KB

In [26]:
features=['Race','Marital Status','T Stage ','N Stage','6th Stage','differentiate','Grade']
data2=get_dummies(data,columns=features)

In [27]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 37 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Age                                      4024 non-null   int64
 1   A Stage                                  4024 non-null   int64
 2   Tumor Size                               4024 non-null   int64
 3   Estrogen Status                          4024 non-null   int64
 4   Progesterone Status                      4024 non-null   int64
 5   Regional Node Examined                   4024 non-null   int64
 6   Reginol Node Positive                    4024 non-null   int64
 7   Survival Months                          4024 non-null   int64
 8   Status                                   4024 non-null   int64
 9   Race_Black                               4024 non-null   bool
 10  Race_Other                               4024 non-null   bool
 11  Race_White                               4024 non-null   bool
 12  Marital Status_Divorced                  4024 non-null   bool
 13  Marital Status_Married                   4024 non-null   bool
 14  Marital Status_Separated                 4024 non-null   bool
 15  Marital Status_Single                    4024 non-null   bool
 16  Marital Status_Widowed                   4024 non-null   bool
 17  T Stage _T1                              4024 non-null   bool
 18  T Stage _T2                              4024 non-null   bool
 19  T Stage _T3                              4024 non-null   bool
 20  T Stage _T4                              4024 non-null   bool
 21  N Stage_N1                               4024 non-null   bool
 22  N Stage_N2                               4024 non-null   bool
 23  N Stage_N3                               4024 non-null   bool
 24  6th Stage_IIA                            4024 non-null   bool
 25  6th Stage_IIB                            4024 non-null   bool
 26  6th Stage_IIIA                           4024 non-null   bool
 27  6th Stage_IIIB                           4024 non-null   bool
 28  6th Stage_IIIC                           4024 non-null   bool
 29  differentiate_Moderately differentiated  4024 non-null   bool
 30  differentiate_Poorly differentiated      4024 non-null   bool
 31  differentiate_Undifferentiated           4024 non-null   bool
 32  differentiate_Well differentiated        4024 non-null   bool
 33  Grade_ anaplastic; Grade IV              4024 non-null   bool
 34  Grade_1                                  4024 non-null   bool
 35  Grade_2                                  4024 non-null   bool
 36  Grade_3                                  4024 non-null   bool
dtypes: bool(28), int64(9)
memory usage: 393.1 KB

In [28]:
Y=data2['Status'] # Dependent variable
X=data2.drop('Status',axis=1) # Axis=1 drop column, Independent columns/ dataset

In [29]:
X.shape

(4024, 36)

In [30]:
Y.shape

(4024,)

In [31]:
X_scaled= StandardScaler().fit_transform(X)

In [32]:
DataFrame(X_scaled)

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,1.565253,-0.152963,-1.253661,-0.267652,-0.458107,1.190676,-0.618172,-0.492961,-0.279201,-0.293927,...,-0.130123,-0.364531,-1.185437,1.619247,-0.068877,-0.394955,-0.068877,-0.394955,-1.185437,1.619247
1,-0.443222,-0.152963,0.214345,-0.267652,-0.458107,-0.044095,0.164807,-0.405695,-0.279201,-0.293927,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
2,0.449434,-0.152963,1.540287,-0.267652,-0.458107,-0.044095,0.556296,0.161530,-0.279201,-0.293927,...,-0.130123,2.743251,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
3,0.449434,-0.152963,-0.590691,-0.267652,-0.458107,-1.525820,-0.618172,0.554224,-0.279201,-0.293927,...,-0.130123,-0.364531,-1.185437,1.619247,-0.068877,-0.394955,-0.068877,-0.394955,-1.185437,1.619247
4,-0.777968,-0.152963,0.498475,-0.267652,-0.458107,-1.402343,-0.618172,-0.929288,-0.279201,-0.293927,...,-0.130123,-0.364531,-1.185437,1.619247,-0.068877,-0.394955,-0.068877,-0.394955,-1.185437,1.619247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4019,0.895761,-0.152963,-1.016886,-0.267652,-0.458107,-1.649297,-0.618172,-0.972921,-0.279201,3.402205,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
4020,0.226270,-0.152963,0.735251,-0.267652,-0.458107,-0.044095,0.752041,-0.100266,-0.279201,-0.293927,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
4021,1.565253,-0.152963,-0.401271,-0.267652,2.182898,-0.414526,-0.226682,-0.100266,-0.279201,-0.293927,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
4022,0.449434,-0.152963,0.640541,-0.267652,-0.458107,-0.414526,-0.618172,0.030632,3.581645,-0.293927,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571
4023,-0.889550,-0.152963,-0.022430,-0.267652,-0.458107,-0.908434,-0.422427,1.252348,-0.279201,-0.293927,...,-0.130123,-0.364531,0.843571,-0.617571,-0.068877,-0.394955,-0.068877,-0.394955,0.843571,-0.617571

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size = 0.3, random_state = 100)

In [34]:
X_train.shape

(2816, 36)

In [35]:
Y_train.shape

(2816,)

In [36]:
Y_train.value_counts()

Status
0    2370
1     446
Name: count, dtype: int64

In [37]:
smote=SMOTE(random_state=100)

In [38]:
X_train, Y_train =smote.fit_resample(X_train, Y_train)

In [39]:
Y_train.value_counts()

Status
0    2370
1    2370
Name: count, dtype: int64

In [40]:
X_train.shape

(4740, 36)