<a href="https://colab.research.google.com/github/Dheer08/Google-Colab/blob/main/Lecture_Data_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Loading Libraries
from pandas import read_csv, get_dummies, DataFrame
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# Decsriptive Statistics

In [ ]:
data=read_csv('/content/Emloyees.csv')

In [ ]:
data

,Age,PastEmployee,BusinessTravel,Department,DistanceFromHome,EducationField,EnvironmentSatisfaction,Gender,JobRole,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime
0,46,No,Travel_Rarely,Human Resources,5,Medical,2,Male,Human Resources,Divorced,5021,8,Yes
1,37,Yes,Travel_Rarely,Human Resources,6,Human Resources,3,Male,Human Resources,Divorced,2073,4,Yes
2,59,No,Non-Travel,Human Resources,2,Human Resources,3,Female,Manager,Married,18844,9,No
3,54,No,Non-Travel,Human Resources,26,Human Resources,4,Female,Manager,Single,17328,2,Yes
4,26,No,Travel_Rarely,Human Resources,25,Life Sciences,3,Female,Human Resources,Married,2942,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,45,No,Travel_Rarely,Sales,20,Life Sciences,4,Female,Sales Executive,Single,4850,8,No
1466,50,Yes,Travel_Rarely,Sales,28,Marketing,4,Male,Sales Executive,Divorced,10854,4,Yes
1467,39,No,Travel_Rarely,Sales,24,Marketing,2,Female,Sales Executive,Married,12031,0,No
1468,26,No,Travel_Rarely,Sales,5,Other,4,Female,Sales Representative,Single,2966,0,No
1469,49,No,Travel_Frequently,Sales,2,Medical,4,Male,Sales Executive,Married,5390,2,No

In [ ]:
data.describe() # Descriptive Statistics

,Age,DistanceFromHome,EnvironmentSatisfaction,MonthlyIncome,NumCompaniesWorked
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,9.192517,2.721769,6502.931293,2.693197
std,9.135373,8.106864,1.093082,4707.956783,2.498009
min,18.000000,1.000000,1.000000,1009.000000,0.000000
25%,30.000000,2.000000,2.000000,2911.000000,1.000000
50%,36.000000,7.000000,3.000000,4919.000000,2.000000
75%,43.000000,14.000000,4.000000,8379.000000,4.000000
max,60.000000,29.000000,4.000000,19999.000000,9.000000

In [ ]:
data.shape # Dimension of the Dataset

(1470, 13)

In [ ]:
data.info() # Description about the data types of columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   PastEmployee             1470 non-null   object
 2   BusinessTravel           1470 non-null   object
 3   Department               1470 non-null   object
 4   DistanceFromHome         1470 non-null   int64
 5   EducationField           1470 non-null   object
 6   EnvironmentSatisfaction  1470 non-null   int64
 7   Gender                   1470 non-null   object
 8   JobRole                  1470 non-null   object
 9   MaritalStatus            1470 non-null   object
 10  MonthlyIncome            1470 non-null   int64
 11  NumCompaniesWorked       1470 non-null   int64
 12  OverTime                 1470 non-null   object
dtypes: int64(5), object(8)
memory usage: 149.4+ KB

## Conversion of categorical columns into numeric values

### Binary

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   PastEmployee             1470 non-null   object
 2   BusinessTravel           1470 non-null   object
 3   Department               1470 non-null   object
 4   DistanceFromHome         1470 non-null   int64
 5   EducationField           1470 non-null   object
 6   EnvironmentSatisfaction  1470 non-null   int64
 7   Gender                   1470 non-null   object
 8   JobRole                  1470 non-null   object
 9   MaritalStatus            1470 non-null   object
 10  MonthlyIncome            1470 non-null   int64
 11  NumCompaniesWorked       1470 non-null   int64
 12  OverTime                 1470 non-null   object
dtypes: int64(5), object(8)
memory usage: 149.4+ KB

In [ ]:
data['PastEmployee'].unique() # Binary

array(['No', 'Yes'], dtype=object)

In [ ]:
data['PastEmployee']=data['PastEmployee'].map({'No':0, 'Yes':1})

In [ ]:
data['PastEmployee']

0       0
1       1
2       0
3       0
4       0
       ..
1465    0
1466    1
1467    0
1468    0
1469    0
Name: PastEmployee, Length: 1470, dtype: int64

In [ ]:
data['Gender'].unique() # Binary

array(['Male', 'Female'], dtype=object)

In [ ]:
data['Gender']=data['Gender'].map({'Male':0, 'Female':1})

In [ ]:
data['OverTime'].unique() # Binary

array(['Yes', 'No'], dtype=object)

In [ ]:
data['OverTime']=data['OverTime'].map({'No':0, 'Yes':1})

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   PastEmployee             1470 non-null   int64
 2   BusinessTravel           1470 non-null   object
 3   Department               1470 non-null   object
 4   DistanceFromHome         1470 non-null   int64
 5   EducationField           1470 non-null   object
 6   EnvironmentSatisfaction  1470 non-null   int64
 7   Gender                   1470 non-null   int64
 8   JobRole                  1470 non-null   object
 9   MaritalStatus            1470 non-null   object
 10  MonthlyIncome            1470 non-null   int64
 11  NumCompaniesWorked       1470 non-null   int64
 12  OverTime                 1470 non-null   int64
dtypes: int64(8), object(5)
memory usage: 149.4+ KB

### Multiple

In [ ]:
data['BusinessTravel'].unique() # Multiple

array(['Travel_Rarely', 'Non-Travel', 'Travel_Frequently'], dtype=object)

In [ ]:
data['Department'].unique() # Multiple

array(['Human Resources', 'Research & Development', 'Sales'], dtype=object)

In [ ]:
data['EducationField'].unique() # Multiple

array(['Medical', 'Human Resources', 'Life Sciences', 'Technical Degree',
       'Other', 'Marketing'], dtype=object)

In [ ]:
data['JobRole'].unique() # Multiple

array(['Human Resources', 'Manager', 'Research Scientist',
       'Laboratory Technician', 'Manufacturing Director',
       'Healthcare Representative', 'Research Director',
       'Sales Executive', 'Sales Representative'], dtype=object)

In [ ]:
data['MaritalStatus'].unique() # Multiple

array(['Divorced', 'Married', 'Single'], dtype=object)

In [ ]:
features=['BusinessTravel','Department','EducationField','JobRole','MaritalStatus']
data2=get_dummies(data,columns=features)

In [ ]:
data2.shape

(1470, 32)

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 32 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   PastEmployee                       1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   EnvironmentSatisfaction            1470 non-null   int64
 4   Gender                             1470 non-null   int64
 5   MonthlyIncome                      1470 non-null   int64
 6   NumCompaniesWorked                 1470 non-null   int64
 7   OverTime                           1470 non-null   int64
 8   BusinessTravel_Non-Travel          1470 non-null   bool
 9   BusinessTravel_Travel_Frequently   1470 non-null   bool
 10  BusinessTravel_Travel_Rarely       1470 non-null   bool
 11  Department_Human Resources         1470 non-null   bool
 12  Department_Research & Development  1470 non-null   bool
 13  Department_Sales                   1470 non-null   bool
 14  EducationField_Human Resources     1470 non-null   bool
 15  EducationField_Life Sciences       1470 non-null   bool
 16  EducationField_Marketing           1470 non-null   bool
 17  EducationField_Medical             1470 non-null   bool
 18  EducationField_Other               1470 non-null   bool
 19  EducationField_Technical Degree    1470 non-null   bool
 20  JobRole_Healthcare Representative  1470 non-null   bool
 21  JobRole_Human Resources            1470 non-null   bool
 22  JobRole_Laboratory Technician      1470 non-null   bool
 23  JobRole_Manager                    1470 non-null   bool
 24  JobRole_Manufacturing Director     1470 non-null   bool
 25  JobRole_Research Director          1470 non-null   bool
 26  JobRole_Research Scientist         1470 non-null   bool
 27  JobRole_Sales Executive            1470 non-null   bool
 28  JobRole_Sales Representative       1470 non-null   bool
 29  MaritalStatus_Divorced             1470 non-null   bool
 30  MaritalStatus_Married              1470 non-null   bool
 31  MaritalStatus_Single               1470 non-null   bool
dtypes: bool(24), int64(8)
memory usage: 126.5 KB

In [ ]:
#data2.to_csv('Data_Prepared')

## Seggregation of datset into Dependent and Independent Variable

In [ ]:
Y=data2['PastEmployee'] # Dependent variable
X=data2.drop('PastEmployee',axis=1) # Axis=1 drop column, Independent columns/ dataset

In [ ]:
X.shape

(1470, 31)

In [ ]:
Y.shape

(1470,)

## Data scaling

In [ ]:
X_scaled= StandardScaler().fit_transform(X)

In [ ]:
DataFrame(X_scaled)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,0.993860,-0.517332,-0.660531,-0.816497,-0.314879,2.125136,1.591746,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,1.869602,-0.918921,-0.685565
1,0.008343,-0.393938,0.254625,-0.816497,-0.941266,0.523316,1.591746,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,1.869602,-0.918921,-0.685565
2,2.417384,-0.887515,0.254625,1.224745,2.622214,2.525591,-0.628241,2.966479,-0.481859,-1.562889,...,-0.462464,3.662208,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,-0.534873,1.088232,-0.685565
3,1.869874,2.073946,1.169781,1.224745,2.300096,-0.277594,1.591746,2.966479,-0.481859,-1.562889,...,-0.462464,3.662208,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,-0.534873,-0.918921,1.458650
4,-1.196177,1.950552,0.254625,1.224745,-0.756622,-0.678049,-0.628241,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,-0.244625,-0.534873,1.088232,-0.685565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,0.884358,1.333581,1.169781,1.224745,-0.351213,2.125136,-0.628241,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,1.873287,-0.244625,-0.534873,-0.918921,1.458650
1466,1.431867,2.320735,1.169781,-0.816497,0.924509,0.523316,1.591746,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,1.873287,-0.244625,1.869602,-0.918921,-0.685565
1467,0.227347,1.827158,-0.660531,1.224745,1.174597,-1.078504,-0.628241,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,1.873287,-0.244625,-0.534873,1.088232,-0.685565
1468,-1.196177,-0.517332,1.169781,1.224745,-0.751522,-1.078504,-0.628241,-0.337100,-0.481859,0.639841,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,-0.533821,4.087890,-0.534873,-0.918921,1.458650
1469,1.322365,-0.887515,1.169781,-0.816497,-0.236474,-0.277594,-0.628241,-0.337100,2.075297,-1.562889,...,-0.462464,-0.273059,-0.330808,-0.239904,-0.497873,1.873287,-0.244625,-0.534873,1.088232,-0.685565

## Splitting the dataset into Train and Test

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size = 0.2, random_state = 100)

In [ ]:
X_train.shape

(1176, 31)

In [ ]:
X_test.shape

(294, 31)

In [ ]:
1470-294

1176

## Data balancing

In [ ]:
Y_train.value_counts()

PastEmployee
0    987
1    189
Name: count, dtype: int64

In [ ]:
smote=SMOTE(random_state=100)

In [ ]:
X_train, Y_train =smote.fit_resample(X_train, Y_train)

In [ ]:
Y_train.value_counts()

PastEmployee
0    987
1    987
Name: count, dtype: int64